image: Visual Studio 2017

install:
  - cmd: git submodule update --init --recursive

configuration: Debug

build: off

skip_branch_with_pr: true

environment:
  vsuffix: alpha$(APPVEYOR_BUILD_NUMBER)
  is_prerelease: true

before_build:
  - cmd: cd Keyczar
  - cmd: msbuild /t:restore /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

build_script:
  - cmd: msbuild /p:Configuration=%configuration% /p:VersionSuffix="%vsuffix%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

before_test:
  - cmd: nunit3-console --noresult --labels=On --workers=1 --stoponerror --where "cat == Create" KeyczarTest\bin\%configuration%\net451\KeyczarTest.dll

test:
  categories:
    except:
      - Performance
      - Create

artifacts:
  - path: Keyczar\Keyczar\bin\$(configuration)\*.nupkg
    name: Keyczar
  - path: Keyczar\KeyczarTool.Minified\bin\$(configuration)\*.nupkg
    name: KeyczarTool

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/keyczar-dotnet-ci/api/v2/package
    api_key:
      secure: qeW4Vpu7ZxccbJAZz215XBKpSTlIXEyZTfi/r+gmEGRxC/zsxHkBexycRjKbfptZ
    skip_symbols: false
    symbol_server: https://www.myget.org/F/keyczar-dotnet-ci/symbols/api/v2/package

  - provider: GitHub
    
    artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
    description: 'Release description'
    auth_token:
      secure: JyJYSgeJYFmkaFy7Gro2dQyv/fqZwz1EzJmp2Nf99H6HUpxNR7ilA/OGPcQk0pA8
    draft: true
    prerelease: $(is_prerelease)
    on:
      appveyor_repo_tag: true       # deploy on tag push only

for:
  - branches:
        except:
          - /v.*/
  - branches:
        only:
          - /v.*-beta/
    environment:
      vsuffix: beta$(APPVEYOR_BUILD_NUMBER)
      is_prerelease: true
  - branches:
        only:
          - /v[\d,.]*/
    configuration: Release
    environment:
      vsuffix: $(APPVEYOR_BUILD_NUMBER)
      is_prerelease: false


