image: Visual Studio 2017

install:
  - cmd: git submodule update --init --recursive
  - cmd: dotnet tool install --global dotnet-warp

configuration: Debug

build: off
test: off

skip_branch_with_pr: true

environment:
  vsuffix: alpha$(APPVEYOR_BUILD_NUMBER)
  vmid: "-"
  is_prerelease: true
  github_deploy: false 

before_build:
  - ps: "[xml]$XmlDocument = Get-Content -Path Keyczar\Directory.Build.Props"
  - ps: $env:vprefix = $XmlDocument.Project.PropertyGroup.VersionPrefix.InnerText
  - cmd: cd Keyczar
  - cmd: msbuild /t:restore /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

build_script:
  - cmd: msbuild /p:Configuration=%configuration% /p:VersionSuffix="%vsuffix%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: cd KeyczarTool
  - cmd: dotnet-warp --verbose -o "keyczar-win-x64.exe" -p "targetframework=netcoreapp2.1;VersionSuffix="%vsuffix%"
  - cmd: cd ..

test_script:
  - cmd: dotnet test --no-build --verbosity="normal" -c %configuration% -f netcoreapp2.1 --filter "TestCategory=Create" --logger Appveyor KeyczarTest\KeyczarTest.csproj
  - cmd: dotnet test --no-build --verbosity="normal" -c %configuration% -f netcoreapp2.1 --filter "(TestCategory!=Create)&(TestCategory!=Performance)" --logger Appveyor KeyczarTest\KeyczarTest.csproj
  - cmd: nunit3-console --result="myresults.xml;format=AppVeyor" --labels=On  --where="cat != Create  && cat != Performance"  KeyczarTest\bin\%configuration%\net451\KeyczarTestNetFrwk.dll

artifacts:
  - path: Keyczar\Keyczar\bin\$(configuration)\*.*nupkg
    name: Keyczar
  - path: Keyczar\KeyczarTool\bin\$(configuration)\*.nupkg
    name: dotnet-keyczar
  - path: Keyczar\KeyczarTool\keyczar-win-x64.exe
    name: dotnet-keyczar-win-x64
deploy:
  - provider: NuGet
    server: https://www.myget.org/F/keyczar-dotnet-ci/api/v2/package
    api_key:
      secure: qeW4Vpu7ZxccbJAZz215XBKpSTlIXEyZTfi/r+gmEGRxC/zsxHkBexycRjKbfptZ
    skip_symbols: false
    symbol_server: https://www.myget.org/F/keyczar-dotnet-ci/symbols/api/v2/package
    artifact: /.*\.[s]*nupkg/ 
  - provider: GitHub
    tag: v$(vprefix)$(vmid)$(vsuffix)
    description: 'Release description'
    auth_token:
      secure: JyJYSgeJYFmkaFy7Gro2dQyv/fqZwz1EzJmp2Nf99H6HUpxNR7ilA/OGPcQk0pA8
    draft: true
    prerelease: $(is_prerelease)
    on:
      github_deploy: true     

for:
  - branches:
      only:
        - /deploy-v.*-beta.*/
    environment:
      vsuffix: beta$(APPVEYOR_BUILD_NUMBER)
      is_prerelease: true
  - branches:
      only:
        - /deploy-v[\d,.]*/
    configuration: Release
    environment:
      vsuffix: $(APPVEYOR_BUILD_NUMBER)
      vmid: "."
      is_prerelease: false
      github_deploy: true

