# Travis-CI Build for keyczar-dotnet 
# see travis-ci.org for details

language: csharp

dotnet: 2.1.400
mono: 5.10.1

matrix:
  include:
    - os: osx
      osx_image: xcode9   
    - os: linux
      dist: trusty
      sudo: required
solution: Keyczar/Keyczar.sln

install:
  - cd Keyczar/
  - msbuild /t:restore

script:
 - msbuild
 - dotnet test -f netcoreapp2.1  --filter "TestCategory=Create" KeyczarTest\KeyczarTest.csproj
 - dotnet test -f netcoreapp2.1  --filter "(TestCategory!=Create)&(TestCategory!=Performance)" KeyczarTest\KeyczarTest.csproj
branches:
  only:
    - master