name: Build .net core

on: [push]

jobs:
  build:
    name: Test ${{ matrix.os }} for dotnet ${{ matrix.dotnet }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet: [ '8.0.x' ]
        os: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Build with dotnet core
      run: dotnet build --configuration Release Keyczar/Keyczar.sln
    - name: Tests Create
      run: dotnet test Keyczar/KeyczarTest/KeyczarTest.csproj --configuration Release --no-build --no-restore --filter="TestCategory=Create"
    - name: Tests
      run: dotnet test Keyczar/KeyczarTest/KeyczarTest.csproj --configuration Release --no-build --no-restore --filter="(TestCategory!=Create)&(TestCategory!=Performance)"
